services:
  autoreg:
    image: autoreg:latest
    build: .
    container_name: autoreg
    ports:
      - "6901:6901"
    shm_size: "2gb"
    environment:
      - VNC_PW=senha_segura
      - VNCOPTIONS=-disableBasicAuth
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/michel/code/AutoReg:/home/kasm-user/.autoreg
      - /home/michel/AutoReg:/home/kasm-user/AutoReg
      - /home/michel/code/Autoreg-web:/home/kasm-user/Autoreg-web

    restart: unless-stopped
